### ISSUE TITLE
About the http api

### ISSUE THREAD

**Issue by volitantns** [caiguanhao/js-obfuscator#10]
hi,

Do you plan to make a version which use http://www.javascriptobfuscator.com/download/JavaScriptObfuscator-JSAPI-Sample.zip ?

there's no any documents

**Comment by caiguanhao** [comment]
No. I made this plugin because it has free online services. I don't want to pay the membership every month. If the website closes the free services, this plugin is useless. If I had to use their APIs, I'd rather start a new project, but I can't afford the premium membership (so I can't test the code).
